# Generated by Django 5.2.5 on 2025-10-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
    ]
